### ISSUE TITLE
建议在《环境变量》的设置中对配置的修改，体现在每次构建的《yml配置》中

### ISSUE THREAD

**Issue by XTShow** [FlowCI/flow-core-x#185]
在《工作流设置》的《环境变量》中，如果对键值进行了修改，构建时会生效，但是构建列表中每次构建的《yml配置》中并没有变化，仍然是《配置yml工作流》中的内容。
建议将每次构建中的《yml配置》修改为真正生效的内容，最好单独展示每个环境变量的当前值，更容易判断构建的配置，谢谢！

**Comment by qhfir** [comment]
谢谢提醒，这块我们考虑不在“工作流设置-环境变量”中显示 yml 工作流中配置的环境变量，在哪里添加就在哪里修改。
