### ISSUE TITLE
[Plugin] 插件开发记录列表

### ISSUE THREAD

**Issue by yunheli** [FlowCI/flow-core-x#268]
- [ ] ruby-runtime
- [ ] node-runtime
- [ ]  git-clone
- [ ] fastline
- [ ] maven-install
- [ ] dingding

- [ ] artifact-upload

**Comment by shaotianchi** [comment]
是否可以加个 python-runtime

**Comment by ckt1010** [comment]
你好，后续考虑添加类似jenkins的Monitor View功能吗？

**Comment by zhiwoeryi** [comment]
你这个插件的意思是，运行环境？

**Comment by zhiwoeryi** [comment]
你们有没有类似于jenkins插件的功能的封装，想学习一下的，我看代码里面有一个模块，但是去看了一下代码，并不像jenkins那样，貌似是下载docker镜像之类的，估计应该是安装运行环境吧

**Comment by zhiwoeryi** [comment]
你们对哪方面有研究过吗？能不能指导一下，非常感谢

**Comment by huhgyong** [comment]
钉钉的意见集成了吗？

**Comment by yang-guo-2016** [comment]
@huhgyong 指是发钉钉的消息插件 ？
