### ISSUE TITLE
持续构建这块如何支持.net/.netcore 项目?

### ISSUE THREAD

**Issue by misaya** [FlowCI/flow-core-x#298]

**Comment by yunheli** [comment]
@duotai .net/.netcore 项目能通过shell命令构建么？

**Comment by yunheli** [comment]
@duotai 如果能通过shell命令构建，那只需要agent跑的机器中支持对应的环境即可

**Comment by duotai** [comment]
dotnet core 可以使用```terminal```|```cmd```|```shell```带进行构建:

```
dotnet publish -c Release -o ../output/
```

**Comment by yang-guo-2016** [comment]
@duotai 可以在 YML 配置文件中直接使用 构建脚本即可

**Comment by duotai** [comment]
@yang-guo-2016   I will have a test about this and make a pull request to the sample repo, could you help me with your  FLOWCI already deployed ?
