### ISSUE TITLE
从docker启动不了，会自动退出

### ISSUE THREAD

**Issue by foooooops** [FlowCI/flow-core-x#312]
执行 ./start-services.sh 到最后会出现 docker_flow.ci_1 exited with code 1 ，然后就只能进入到登录界面，输入账号密码之后点击登录没反应。
执行 ./start-services.sh 后控制台输出：
##############Start Update Docker Images###################
latest: Pulling from flowci/flow-platform
Digest: sha256:77c62602e561d3e582d9d42beed484f208218d4566ef16adf9279af335fe6c2a
Status: Image is up to date for flowci/flow-platform:latest
latest: Pulling from flowci/flow-web
Digest: sha256:0d6873b97a33ae9088870e3772c5890c7d45a08b551e2137c6c7387cf7500361
Status: Image is up to date for flowci/flow-web:latest
##############Finish Update Docker Images###################
###########环境变量说明###########
MYSQL_USER: 配置的Mysql的初始用户名, 默认是 root , 不可修改
JVM 最大堆大小为 1.5G
Mysql 的 默认存储路径是 /root/data/flowci/mysql , 假如您正式部署请选择正确的配置路径
MYSQL_PASSWORD: 配置的Mysql的初始密码, 默认是 flow.ci , 当前参数是 flow.ci
MYSQL_HOST: 配置的Mysql的HOST地址, 默认是 127.0.0.1 , 当前参数是 127.0.0.1
FLOW_API_DOMAIN: 部署的FlowApi地址, 默认是 127.0.0.1, 当前参数值是 127.0.0.1
FLOW_WEB_DOMAIN: 部署的FlowWeb地址, 默认是 127.0.0.1, 当前参数值是 127.0.0.1
FLOW_SYS_EMAIL: Flow 的系统账号， 默认是 admin@flow.ci, 当前参数值是 admin@flow.ci
FLOW_SYS_USERNAME: Flow 的系统用户名， 默认是 admin, 当前参数值是 admin
FLOW_SYS_PASSWORD: Flow 的系统密码， 默认是 123456, 当前参数值是 123456
Starting docker_flow.ci_1 ... done
Starting docker_flow.web_1 ... done
Attaching to docker_flow.ci_1, docker_flow.web_1
flow.ci_1   | Starting MariaDB database server: mysqld.
flow.ci_1   | mysql is up
flow.ci_1   | running migration
flow.ci_1   | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
flow.ci_1   | Flyway 4.2.0 by Boxfuse
flow.ci_1   | 
flow.ci_1   | Database: jdbc:mysql://127.0.0.1:3306/flow_api_db (MySQL 10.1)
flow.ci_1   | Successfully validated 4 migrations (execution time 00:00.018s)
flow.ci_1   | Current version of schema `flow_api_db`: 1.4
flow.ci_1   | Schema `flow_api_db` is up to date. No migration necessary.
flow.ci_1   | Flyway 4.2.0 by Boxfuse
flow.ci_1   | 
flow.ci_1   | Database: jdbc:mysql://127.0.0.1:3306/flow_cc_db (MySQL 10.1)
flow.ci_1   | Successfully validated 2 migrations (execution time 00:00.015s)
flow.ci_1   | Current version of schema `flow_cc_db`: 1.1
flow.ci_1   | Schema `flow_cc_db` is up to date. No migration necessary.
flow.ci_1   | finish migration
flow.ci_1   | Starting Docker: docker.
flow.ci_1   | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Cannot allocate memory' (errno=12)
flow.ci_1   | #
flow.ci_1   | # There is insufficient memory for the Java Runtime Environment to continue.
flow.ci_1   | # Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
flow.ci_1   | # Can not save log file, dump to screen..
flow.ci_1   | #
flow.ci_1   | # There is insufficient memory for the Java Runtime Environment to continue.
flow.ci_1   | # Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
flow.ci_1   | # Possible reasons:
flow.ci_1   | #   The system is out of physical RAM or swap space
flow.ci_1   | #   In 32 bit mode, the process size limit was hit
flow.ci_1   | # Possible solutions:
flow.ci_1   | #   Reduce memory load on the system
flow.ci_1   | #   Increase physical memory or swap space
flow.ci_1   | #   Check if swap backing store is full
flow.ci_1   | #   Use 64 bit Java on a 64 bit OS
flow.ci_1   | #   Decrease Java heap size (-Xmx/-Xms)
flow.ci_1   | #   Decrease number of Java threads
flow.ci_1   | #   Decrease Java thread stack sizes (-Xss)
flow.ci_1   | #   Set larger code cache with -XX:ReservedCodeCacheSize=
flow.ci_1   | # This output file may be truncated or incomplete.
flow.ci_1   | #
flow.ci_1   | #  Out of Memory Error (os_linux.cpp:2643), pid=5, tid=0x00007f0c877e7700
flow.ci_1   | #
flow.ci_1   | # JRE version:  (8.0_151-b12) (build )
flow.ci_1   | # Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
flow.ci_1   | # Core dump written. Default location: /etc/flow.ci/core or core.5
flow.ci_1   | #
flow.ci_1   | 
flow.ci_1   | ---------------  T H R E A D  ---------------
flow.ci_1   | 
flow.ci_1   | Current thread (0x00007f0c8000a800):  JavaThread "Unknown thread" [_thread_in_vm, id=355, stack(0x00007f0c876e7000,0x00007f0c877e8000)]
flow.ci_1   | 
flow.ci_1   | Stack: [0x00007f0c876e7000,0x00007f0c877e8000],  sp=0x00007f0c877e64e0,  free space=1021k
flow.ci_1   | Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
flow.ci_1   | V  [libjvm.so+0xa6b440]
flow.ci_1   | V  [libjvm.so+0x4c680c]
flow.ci_1   | V  [libjvm.so+0x8bab70]
flow.ci_1   | V  [libjvm.so+0x8b51fe]
flow.ci_1   | V  [libjvm.so+0xa68034]
flow.ci_1   | V  [libjvm.so+0x5ca1a0]
flow.ci_1   | V  [libjvm.so+0xa07a34]
flow.ci_1   | V  [libjvm.so+0x5caf3a]
flow.ci_1   | V  [libjvm.so+0x5b675f]
flow.ci_1   | V  [libjvm.so+0xa2f731]
flow.ci_1   | V  [libjvm.so+0xa2f992]
flow.ci_1   | V  [libjvm.so+0x60f14f]
flow.ci_1   | V  [libjvm.so+0xa1420a]
flow.ci_1   | V  [libjvm.so+0x6891d1]  JNI_CreateJavaVM+0x61
flow.ci_1   | C  [libjli.so+0x2f06]
flow.ci_1   | C  [libjli.so+0x748d]
flow.ci_1   | C  [libpthread.so.0+0x7494]  start_thread+0xc4
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | ---------------  P R O C E S S  ---------------
flow.ci_1   | 
flow.ci_1   | Java Threads: ( => current thread )
flow.ci_1   | 
flow.ci_1   | Other Threads:
flow.ci_1   | 
flow.ci_1   | =>0x00007f0c8000a800 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=355, stack(0x00007f0c876e7000,0x00007f0c877e8000)]
flow.ci_1   | 
flow.ci_1   | VM state:not at safepoint (not fully initialized)
flow.ci_1   | 
flow.ci_1   | VM Mutex/Monitor currently owned by a thread: None
flow.ci_1   | 
flow.ci_1   | GC Heap History (0 events):
flow.ci_1   | No events
flow.ci_1   | 
flow.ci_1   | Deoptimization events (0 events):
flow.ci_1   | No events
flow.ci_1   | 
flow.ci_1   | Internal exceptions (0 events):
flow.ci_1   | No events
flow.ci_1   | 
flow.ci_1   | Events (0 events):
flow.ci_1   | No events
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | Dynamic libraries:
flow.ci_1   | a0000000-c0000000 rw-p 00000000 00:00 0 
flow.ci_1   | 56131ecfa000-56131ecfb000 r-xp 00000000 fd:01 501385                     /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
flow.ci_1   | 56131eefa000-56131eefb000 r--p 00000000 fd:01 501385                     /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
flow.ci_1   | 56131eefb000-56131eefc000 rw-p 00001000 fd:01 501385                     /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
flow.ci_1   | 56131f106000-56131f127000 rw-p 00000000 00:00 0                          [heap]
flow.ci_1   | 7f0c7093f000-7f0c70a3f000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c70a3f000-7f0c70c3f000 ---p 00000000 00:00 0 
flow.ci_1   | 7f0c70c3f000-7f0c70c4a000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c70c4a000-7f0c71000000 ---p 00000000 00:00 0 
flow.ci_1   | 7f0c71000000-7f0c71270000 rwxp 00000000 00:00 0 
flow.ci_1   | 7f0c71270000-7f0c80000000 ---p 00000000 00:00 0 
flow.ci_1   | 7f0c80000000-7f0c80033000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c80033000-7f0c84000000 ---p 00000000 00:00 0 
flow.ci_1   | 7f0c8417d000-7f0c84185000 r-xp 00000000 fd:01 501437                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
flow.ci_1   | 7f0c84185000-7f0c84384000 ---p 00008000 fd:01 501437                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
flow.ci_1   | 7f0c84384000-7f0c84385000 r--p 00007000 fd:01 501437                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
flow.ci_1   | 7f0c84385000-7f0c84386000 rw-p 00008000 fd:01 501437                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
flow.ci_1   | 7f0c84386000-7f0c84390000 r-xp 00000000 fd:01 279495                     /usr/lib/x86_64-linux-gnu/libnss_files-2.24.so
flow.ci_1   | 7f0c84390000-7f0c84590000 ---p 0000a000 fd:01 279495                     /usr/lib/x86_64-linux-gnu/libnss_files-2.24.so
flow.ci_1   | 7f0c84590000-7f0c84591000 r--p 0000a000 fd:01 279495                     /usr/lib/x86_64-linux-gnu/libnss_files-2.24.so
flow.ci_1   | 7f0c84591000-7f0c84592000 rw-p 0000b000 fd:01 279495                     /usr/lib/x86_64-linux-gnu/libnss_files-2.24.so
flow.ci_1   | 7f0c84592000-7f0c84598000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c84598000-7f0c845a3000 r-xp 00000000 fd:01 279499                     /usr/lib/x86_64-linux-gnu/libnss_nis-2.24.so
flow.ci_1   | 7f0c845a3000-7f0c847a2000 ---p 0000b000 fd:01 279499                     /usr/lib/x86_64-linux-gnu/libnss_nis-2.24.so
flow.ci_1   | 7f0c847a2000-7f0c847a3000 r--p 0000a000 fd:01 279499                     /usr/lib/x86_64-linux-gnu/libnss_nis-2.24.so
flow.ci_1   | 7f0c847a3000-7f0c847a4000 rw-p 0000b000 fd:01 279499                     /usr/lib/x86_64-linux-gnu/libnss_nis-2.24.so
flow.ci_1   | 7f0c847a4000-7f0c847b8000 r-xp 00000000 fd:01 279489                     /usr/lib/x86_64-linux-gnu/libnsl-2.24.so
flow.ci_1   | 7f0c847b8000-7f0c849b8000 ---p 00014000 fd:01 279489                     /usr/lib/x86_64-linux-gnu/libnsl-2.24.so
flow.ci_1   | 7f0c849b8000-7f0c849b9000 r--p 00014000 fd:01 279489                     /usr/lib/x86_64-linux-gnu/libnsl-2.24.so
flow.ci_1   | 7f0c849b9000-7f0c849ba000 rw-p 00015000 fd:01 279489                     /usr/lib/x86_64-linux-gnu/libnsl-2.24.so
flow.ci_1   | 7f0c849ba000-7f0c849bc000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c849bc000-7f0c849c3000 r-xp 00000000 fd:01 279491                     /usr/lib/x86_64-linux-gnu/libnss_compat-2.24.so
flow.ci_1   | 7f0c849c3000-7f0c84bc2000 ---p 00007000 fd:01 279491                     /usr/lib/x86_64-linux-gnu/libnss_compat-2.24.so
flow.ci_1   | 7f0c84bc2000-7f0c84bc3000 r--p 00006000 fd:01 279491                     /usr/lib/x86_64-linux-gnu/libnss_compat-2.24.so
flow.ci_1   | 7f0c84bc3000-7f0c84bc4000 rw-p 00007000 fd:01 279491                     /usr/lib/x86_64-linux-gnu/libnss_compat-2.24.so
flow.ci_1   | 7f0c84bc4000-7f0c84bf1000 r-xp 00000000 fd:01 501416                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
flow.ci_1   | 7f0c84bf1000-7f0c84df0000 ---p 0002d000 fd:01 501416                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
flow.ci_1   | 7f0c84df0000-7f0c84df1000 r--p 0002c000 fd:01 501416                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
flow.ci_1   | 7f0c84df1000-7f0c84df3000 rw-p 0002d000 fd:01 501416                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
flow.ci_1   | 7f0c84df3000-7f0c84e02000 r-xp 00000000 fd:01 501436                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
flow.ci_1   | 7f0c84e02000-7f0c85002000 ---p 0000f000 fd:01 501436                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
flow.ci_1   | 7f0c85002000-7f0c85004000 r--p 0000f000 fd:01 501436                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
flow.ci_1   | 7f0c85004000-7f0c85005000 rw-p 00011000 fd:01 501436                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
flow.ci_1   | 7f0c85005000-7f0c8500c000 r-xp 00000000 fd:01 279520                     /usr/lib/x86_64-linux-gnu/librt-2.24.so
flow.ci_1   | 7f0c8500c000-7f0c8520b000 ---p 00007000 fd:01 279520                     /usr/lib/x86_64-linux-gnu/librt-2.24.so
flow.ci_1   | 7f0c8520b000-7f0c8520c000 r--p 00006000 fd:01 279520                     /usr/lib/x86_64-linux-gnu/librt-2.24.so
flow.ci_1   | 7f0c8520c000-7f0c8520d000 rw-p 00007000 fd:01 279520                     /usr/lib/x86_64-linux-gnu/librt-2.24.so
flow.ci_1   | 7f0c8520d000-7f0c85223000 r-xp 00000000 fd:01 279467                     /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
flow.ci_1   | 7f0c85223000-7f0c85422000 ---p 00016000 fd:01 279467                     /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
flow.ci_1   | 7f0c85422000-7f0c85423000 r--p 00015000 fd:01 279467                     /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
flow.ci_1   | 7f0c85423000-7f0c85424000 rw-p 00016000 fd:01 279467                     /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
flow.ci_1   | 7f0c85424000-7f0c85527000 r-xp 00000000 fd:01 279476                     /usr/lib/x86_64-linux-gnu/libm-2.24.so
flow.ci_1   | 7f0c85527000-7f0c85726000 ---p 00103000 fd:01 279476                     /usr/lib/x86_64-linux-gnu/libm-2.24.so
flow.ci_1   | 7f0c85726000-7f0c85727000 r--p 00102000 fd:01 279476                     /usr/lib/x86_64-linux-gnu/libm-2.24.so
flow.ci_1   | 7f0c85727000-7f0c85728000 rw-p 00103000 fd:01 279476                     /usr/lib/x86_64-linux-gnu/libm-2.24.so
flow.ci_1   | 7f0c85728000-7f0c8589a000 r-xp 00000000 fd:01 279530                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
flow.ci_1   | 7f0c8589a000-7f0c85a9a000 ---p 00172000 fd:01 279530                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
flow.ci_1   | 7f0c85a9a000-7f0c85aa4000 r--p 00172000 fd:01 279530                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
flow.ci_1   | 7f0c85aa4000-7f0c85aa6000 rw-p 0017c000 fd:01 279530                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
flow.ci_1   | 7f0c85aa6000-7f0c85aaa000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c85aaa000-7f0c866fe000 r-xp 00000000 fd:01 501442                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
flow.ci_1   | 7f0c866fe000-7f0c868fd000 ---p 00c54000 fd:01 501442                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
flow.ci_1   | 7f0c868fd000-7f0c86990000 r--p 00c53000 fd:01 501442                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
flow.ci_1   | 7f0c86990000-7f0c869b9000 rw-p 00ce6000 fd:01 501442                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
flow.ci_1   | 7f0c869b9000-7f0c869e9000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c869e9000-7f0c86b7e000 r-xp 00000000 fd:01 279442                     /usr/lib/x86_64-linux-gnu/libc-2.24.so
flow.ci_1   | 7f0c86b7e000-7f0c86d7e000 ---p 00195000 fd:01 279442                     /usr/lib/x86_64-linux-gnu/libc-2.24.so
flow.ci_1   | 7f0c86d7e000-7f0c86d82000 r--p 00195000 fd:01 279442                     /usr/lib/x86_64-linux-gnu/libc-2.24.so
flow.ci_1   | 7f0c86d82000-7f0c86d84000 rw-p 00199000 fd:01 279442                     /usr/lib/x86_64-linux-gnu/libc-2.24.so
flow.ci_1   | 7f0c86d84000-7f0c86d88000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c86d88000-7f0c86d8b000 r-xp 00000000 fd:01 279455                     /usr/lib/x86_64-linux-gnu/libdl-2.24.so
flow.ci_1   | 7f0c86d8b000-7f0c86f8a000 ---p 00003000 fd:01 279455                     /usr/lib/x86_64-linux-gnu/libdl-2.24.so
flow.ci_1   | 7f0c86f8a000-7f0c86f8b000 r--p 00002000 fd:01 279455                     /usr/lib/x86_64-linux-gnu/libdl-2.24.so
flow.ci_1   | 7f0c86f8b000-7f0c86f8c000 rw-p 00003000 fd:01 279455                     /usr/lib/x86_64-linux-gnu/libdl-2.24.so
flow.ci_1   | 7f0c86f8c000-7f0c86f99000 r-xp 00000000 fd:01 501400                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
flow.ci_1   | 7f0c86f99000-7f0c87199000 ---p 0000d000 fd:01 501400                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
flow.ci_1   | 7f0c87199000-7f0c8719a000 r--p 0000d000 fd:01 501400                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
flow.ci_1   | 7f0c8719a000-7f0c8719b000 rw-p 0000e000 fd:01 501400                     /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
flow.ci_1   | 7f0c8719b000-7f0c871b4000 r-xp 00000000 fd:01 279548                     /usr/lib/x86_64-linux-gnu/libz.so.1.2.8
flow.ci_1   | 7f0c871b4000-7f0c873b3000 ---p 00019000 fd:01 279548                     /usr/lib/x86_64-linux-gnu/libz.so.1.2.8
flow.ci_1   | 7f0c873b3000-7f0c873b4000 r--p 00018000 fd:01 279548                     /usr/lib/x86_64-linux-gnu/libz.so.1.2.8
flow.ci_1   | 7f0c873b4000-7f0c873b5000 rw-p 00019000 fd:01 279548                     /usr/lib/x86_64-linux-gnu/libz.so.1.2.8
flow.ci_1   | 7f0c873b5000-7f0c873cd000 r-xp 00000000 fd:01 279516                     /usr/lib/x86_64-linux-gnu/libpthread-2.24.so
flow.ci_1   | 7f0c873cd000-7f0c875cc000 ---p 00018000 fd:01 279516                     /usr/lib/x86_64-linux-gnu/libpthread-2.24.so
flow.ci_1   | 7f0c875cc000-7f0c875cd000 r--p 00017000 fd:01 279516                     /usr/lib/x86_64-linux-gnu/libpthread-2.24.so
flow.ci_1   | 7f0c875cd000-7f0c875ce000 rw-p 00018000 fd:01 279516                     /usr/lib/x86_64-linux-gnu/libpthread-2.24.so
flow.ci_1   | 7f0c875ce000-7f0c875d2000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c875d2000-7f0c875f5000 r-xp 00000000 fd:01 279420                     /usr/lib/x86_64-linux-gnu/ld-2.24.so
flow.ci_1   | 7f0c876df000-7f0c876e7000 rw-s 00000000 fd:01 860249                     /tmp/hsperfdata_root/5
flow.ci_1   | 7f0c876e7000-7f0c876ea000 ---p 00000000 00:00 0 
flow.ci_1   | 7f0c876ea000-7f0c877ec000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c877f0000-7f0c877f1000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c877f1000-7f0c877f2000 r--p 00000000 00:00 0 
flow.ci_1   | 7f0c877f2000-7f0c877f5000 rw-p 00000000 00:00 0 
flow.ci_1   | 7f0c877f5000-7f0c877f6000 r--p 00023000 fd:01 279420                     /usr/lib/x86_64-linux-gnu/ld-2.24.so
flow.ci_1   | 7f0c877f6000-7f0c877f7000 rw-p 00024000 fd:01 279420                     /usr/lib/x86_64-linux-gnu/ld-2.24.so
flow.ci_1   | 7f0c877f7000-7f0c877f8000 rw-p 00000000 00:00 0 
flow.ci_1   | 7ffe4920d000-7ffe4922e000 rw-p 00000000 00:00 0                          [stack]
flow.ci_1   | 7ffe49266000-7ffe49268000 r-xp 00000000 00:00 0                          [vdso]
flow.ci_1   | ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
flow.ci_1   | 
flow.ci_1   | VM Arguments:
flow.ci_1   | jvm_args: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Xms1536m -Xmx1536m -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp 
flow.ci_1   | java_command: org.apache.catalina.startup.Bootstrap start
flow.ci_1   | java_class_path (initial): /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
flow.ci_1   | Launcher Type: SUN_STANDARD
flow.ci_1   | 
flow.ci_1   | Environment Variables:
flow.ci_1   | JAVA_HOME=/docker-java-home/jre
flow.ci_1   | PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
flow.ci_1   | LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib
flow.ci_1   | 
flow.ci_1   | Signal Handlers:
flow.ci_1   | SIGSEGV: [libjvm.so+0xa6bed0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGBUS: [libjvm.so+0xa6bed0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGFPE: [libjvm.so+0x8b6390], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGPIPE: [libjvm.so+0x8b6390], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGXFSZ: [libjvm.so+0x8b6390], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGILL: [libjvm.so+0x8b6390], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGUSR1: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
flow.ci_1   | SIGUSR2: [libjvm.so+0x8b6240], sa_mask[0]=00000000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
flow.ci_1   | SIGHUP: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
flow.ci_1   | SIGINT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
flow.ci_1   | SIGTERM: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
flow.ci_1   | SIGQUIT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | ---------------  S Y S T E M  ---------------
flow.ci_1   | 
flow.ci_1   | OS:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
flow.ci_1   | NAME="Debian GNU/Linux"
flow.ci_1   | VERSION_ID="9"
flow.ci_1   | VERSION="9 (stretch)"
flow.ci_1   | ID=debian
flow.ci_1   | HOME_URL="https://www.debian.org/"
flow.ci_1   | SUPPORT_URL="https://www.debian.org/support"
flow.ci_1   | BUG_REPORT_URL="https://bugs.debian.org/"
flow.ci_1   | 
flow.ci_1   | uname:Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64
flow.ci_1   | libc:glibc 2.24 NPTL 2.24 
flow.ci_1   | rlimit: STACK 8192k, CORE infinity, NPROC infinity, NOFILE 65536, AS infinity
flow.ci_1   | load average:0.00 0.07 0.17
flow.ci_1   | 
flow.ci_1   | /proc/meminfo:
flow.ci_1   | MemTotal:        1016288 kB
flow.ci_1   | MemFree:           95128 kB
flow.ci_1   | MemAvailable:     566044 kB
flow.ci_1   | Buffers:           69708 kB
flow.ci_1   | Cached:           486732 kB
flow.ci_1   | SwapCached:            0 kB
flow.ci_1   | Active:           515204 kB
flow.ci_1   | Inactive:         274376 kB
flow.ci_1   | Active(anon):     233536 kB
flow.ci_1   | Inactive(anon):      120 kB
flow.ci_1   | Active(file):     281668 kB
flow.ci_1   | Inactive(file):   274256 kB
flow.ci_1   | Unevictable:           0 kB
flow.ci_1   | Mlocked:               0 kB
flow.ci_1   | SwapTotal:             0 kB
flow.ci_1   | SwapFree:              0 kB
flow.ci_1   | Dirty:               844 kB
flow.ci_1   | Writeback:             0 kB
flow.ci_1   | AnonPages:        233204 kB
flow.ci_1   | Mapped:            81688 kB
flow.ci_1   | Shmem:               516 kB
flow.ci_1   | Slab:             100400 kB
flow.ci_1   | SReclaimable:      85556 kB
flow.ci_1   | SUnreclaim:        14844 kB
flow.ci_1   | KernelStack:        3152 kB
flow.ci_1   | PageTables:         6740 kB
flow.ci_1   | NFS_Unstable:          0 kB
flow.ci_1   | Bounce:                0 kB
flow.ci_1   | WritebackTmp:          0 kB
flow.ci_1   | CommitLimit:      508144 kB
flow.ci_1   | Committed_AS:    1833692 kB
flow.ci_1   | VmallocTotal:   34359738367 kB
flow.ci_1   | VmallocUsed:        8844 kB
flow.ci_1   | VmallocChunk:   34359719676 kB
flow.ci_1   | HardwareCorrupted:     0 kB
flow.ci_1   | AnonHugePages:     20480 kB
flow.ci_1   | HugePages_Total:       0
flow.ci_1   | HugePages_Free:        0
flow.ci_1   | HugePages_Rsvd:        0
flow.ci_1   | HugePages_Surp:        0
flow.ci_1   | Hugepagesize:       2048 kB
flow.ci_1   | DirectMap4k:       65528 kB
flow.ci_1   | DirectMap2M:      983040 kB
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | CPU:total 1 (initial active 1) (14 cores per cpu, 1 threads per core) family 6 model 79 stepping 1, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, 3dnowpref, lzcnt, tsc, bmi1, bmi2, adx
flow.ci_1   | 
flow.ci_1   | /proc/cpuinfo:
flow.ci_1   | processor	: 0
flow.ci_1   | vendor_id	: GenuineIntel
flow.ci_1   | cpu family	: 6
flow.ci_1   | model		: 79
flow.ci_1   | model name	: Intel(R) Xeon(R) CPU E5-26xx v4
flow.ci_1   | stepping	: 1
flow.ci_1   | microcode	: 0x1
flow.ci_1   | cpu MHz		: 2394.454
flow.ci_1   | cache size	: 4096 KB
flow.ci_1   | physical id	: 0
flow.ci_1   | siblings	: 1
flow.ci_1   | core id		: 0
flow.ci_1   | cpu cores	: 1
flow.ci_1   | apicid		: 0
flow.ci_1   | initial apicid	: 0
flow.ci_1   | fpu		: yes
flow.ci_1   | fpu_exception	: yes
flow.ci_1   | cpuid level	: 13
flow.ci_1   | wp		: yes
flow.ci_1   | flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch bmi1 avx2 bmi2 rdseed adx xsaveopt
flow.ci_1   | bogomips	: 4788.90
flow.ci_1   | clflush size	: 64
flow.ci_1   | cache_alignment	: 64
flow.ci_1   | address sizes	: 40 bits physical, 48 bits virtual
flow.ci_1   | power management:
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | 
flow.ci_1   | Memory: 4k page, physical 1016288k(95128k free), swap 0k(0k free)
flow.ci_1   | 
flow.ci_1   | vm_info: OpenJDK 64-Bit Server VM (25.151-b12) for linux-amd64 JRE (1.8.0_151-8u151-b12-1~deb9u1-b12), built on Nov  1 2017 14:17:57 by "pbuilder" with gcc 6.3.0 20170516
flow.ci_1   | 
flow.ci_1   | time: Thu May 10 09:05:39 2018
flow.ci_1   | elapsed time: 0 seconds (0d 0h 0m 0s)
flow.ci_1   | 
docker_flow.ci_1 exited with code 1

**Comment by foooooops** [comment]
是我配置太低了吗...

**Comment by yunheli** [comment]
@foooooops 上面报的错误 “Cannot allocate memory'”， 修改一下jvm的堆的大小

**Comment by yunheli** [comment]
@foooooops 修改 start_service.sh 里面 Xms1g Xmx1g

**Comment by yunheli** [comment]
或者 512m也行

**Comment by foooooops** [comment]
@yunheli 好的蟹蟹啦
