### ISSUE TITLE
启动报mysql root没有权限ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by vwin** [FlowCI/flow-core-x#322]
![image](https://user-images.githubusercontent.com/5998089/49852622-9dd19700-fe1f-11e8-87bf-b9ef6dcc1b5b.png)

**Comment by yunheli** [comment]
@vwin 设置password了么？

**Comment by yunheli** [comment]
或者在宿主机安装mysql 把 host或者password传递进去

**Comment by vwin** [comment]
必须在宿主机安装mysql吗？

**Comment by yunheli** [comment]
docker里面有内嵌docker，密码要设置

**Comment by yunheli** [comment]
把启动命令打出来？ 宿主机系统？

**Comment by yunheli** [comment]
@vwin 你的宿主机系统？挂载的mysql目录~/flow-ci/data 请保证有ALL权限

**Comment by vwin** [comment]
宿主机是Ubuntu16.04 flow-ci 整个文件夹及其子文件权限都是777

**Comment by yunheli** [comment]
很抱歉，我们查看一下

**Comment by yunheli** [comment]
临时解决方案可以在宿主机安装mysql把 host password传入进去

**Comment by vwin** [comment]
现在就是在宿主机安装的mysql，host password也都传进去了
![image](https://user-images.githubusercontent.com/5998089/49854052-03278700-fe24-11e8-8317-2bf5d90768b8.png)

**Comment by yunheli** [comment]
MYSQL_HOST使用 局域网IP

**Comment by yunheli** [comment]
@vwin 可以么？

**Comment by vwin** [comment]
mysql_host换成局域网ip还是一样的问题~
![image](https://user-images.githubusercontent.com/5998089/49854399-fb1c1700-fe24-11e8-80f2-90fb873a1cee.png)

**Comment by vwin** [comment]
本地访问mysql一切正常~

**Comment by yunheli** [comment]
能再试试 把~/flow-ci 删除，权限不要动，不要设置ALL

**Comment by yunheli** [comment]
@vwin 很抱歉，我修复一下问题，Mysql不使用内部启动的方式，内部启动mysql导致核心模块和宿主机mysql的核心模块产生锁的问题，很抱歉

**Comment by vwin** [comment]
👌，辛苦~
