### ISSUE TITLE
Can it support clone git url like: ssh://git@gitlab.xxx.com/xxx.git 

### ISSUE THREAD

**Issue by cshanxiao** [FlowCI/flow-core-x#342]
I set valid ssh key in gitlab, but it can not clone code, tips: Auth failed.

**Comment by gy2006** [comment]
have you created a secret on the admin page (https://github.com/FlowCI/docs/blob/master/v1.0/git/gitlab.md)?

**Comment by cshanxiao** [comment]
> have you created a secret on the admin page (https://github.com/FlowCI/docs/blob/master/v1.0/git/gitlab.md)?

Yes, I did. I show you the problem attatments, 7 days aviable, please asap：
https://c-t.work/s/6c04408bb6c243

**Comment by gy2006** [comment]
It was a bug on the git test, it has been fixed, thanks 😃 

please try to pull the latest images and docker install repo
```bash
docker pull flowci/core:latest
docker pull flowci/web:latest

git pull https://github.com/FlowCI/docker-install.git
```
