### ISSUE TITLE
可以针对单个step手动启动不？

### ISSUE THREAD

**Issue by genkin-he** [FlowCI/flow-core-x#391]
感谢作者的贡献，我有两个问题想请教下：
1. 可以针对单个step手动启动不？比如部署生产那一步的时候，我们希望可以手动来触发。
2. docker-install 方式安装的可以设置域名吗？我试了下NGINX代理好像不行。
感谢！

**Comment by gy2006** [comment]
谢谢

1. 这个功能正在开发中，目前的版本还不支持
2. 是在宿主机上的 nginx 吗？ docker-install 的方式会把 flow.ci 需要的端口号 mapping 到宿主机上，域名配置的话可以在宿主机上配置，再运行 `./server.sh start yourdomain.com`, 启动后就可以从 yourdomain.com:2015 访问，如果要修改端口的话，可以在 `server.sh` 里面配置

**Comment by genkin-he** [comment]
非常感谢，我尝试一下。

**Comment by gy2006** [comment]
纠正一下，启动命令应该是 `./server.sh -h yourdomain.com start`
启动之后还需要在 Settings -> System 下面检查一下 URL 是否正确，如果不正确的话可以从这里修改
![](https://raw.githubusercontent.com/FlowCI/docs/master/src/config_server_url.png)

**Comment by genkin-he** [comment]
我尝试了好几次，用域名:2015可以访问，但是我想把2015端口代理到域名的80端口上，就不好使了。我想只通过域名不加端口的方式去访问，是不是NGINX漏什么配置了?

**Comment by gy2006** [comment]
也可以直接修改 flow.ci 的端口，在 [`server.sh`](https://github.com/FlowCI/docker-install/blob/master/server.sh) 的 33 行，`export FLOWCI_WEB_PORT=2015` 把端口改成 80 就行

**Comment by genkin-he** [comment]
好的  谢谢！很棒的东西。
