### ISSUE TITLE
Question: How to backup config and flows from server

### ISSUE THREAD

**Issue by luke-riu** [FlowCI/flow-core-x#398]
I am currently running the server on docker. How can I backup/ export my flows etc?
Thanks

**Comment by gy2006** [comment]
it doesn't support backup/export flows from web UI currently.

the default database dir is located at your $HOME dir

https://github.com/FlowCI/docker-install/blob/master/server.sh

```
	## setup data path
	export FLOWCI_DATABASE_DIR="$HOME/.flowci/db"
	export FLOWCI_WORKSPACE_DIR="$HOME/.flowci/ws"
	export FLOWCI_DATA_DIR="$HOME/.flowci/data"
```

so the flows wouldn't be lost after the docker container deleted

**Comment by luke-riu** [comment]
perfect. Thank you
